name: 🧠 Update Daily Fun Fact

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run script
        run: python update_readme.py

      - name: Commit & Push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "varundxd"
          git config --global user.email "varundxd@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/varundxd/varundxd.git
          git add README.md
          git commit -m "🔄 auto: update daily fun fact" || echo "No changes to commit"
          git push origin HEAD:main
